apiVersion: apps/v1
kind: Deployment
metadata:
  name: appA-deployment
  namespace: appA-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appA
  template:
    metadata:
      labels:
        app: appA
    spec:
      containers:
        - name: appA-container
          image: nginx:latest
